spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOSTS}/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
    #     url: "jdbc:postgresql://localhost:5432/postgres"
    #     username: "postgres"
    #     password: "postgres"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 500
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  profiles:
    active: features

management:
  health:
    db:
      enabled: true
